# Generated by Django 2.2.7 on 2019-11-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media')),
                ('facebook', models.CharField(max_length=255)),
            ],
        ),
    ]
