# Generated by Django 2.2.5 on 2019-11-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='facebook',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
