# Generated by Django 2.2.5 on 2019-11-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191112_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
